version: '3.4'

services:
  reactjs-docker-example:
    image: reactjs-docker-example
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
