FROM nginx:1.21.0-alpine as base
LABEL author="Duong Duc Nam <nampt1999@gmail.com>"

FROM node:12.22.1-alpine as build
WORKDIR /app
RUN apk add yarn
RUN npm install react-scripts -g --silent

COPY ["package.json", "yarn.lock", "./"]
RUN yarn install --prod --silent

COPY . .
RUN yarn run build

FROM base
COPY --from=build /app/build /usr/share/nginx/html
COPY ./docker/site.conf /etc/nginx/conf.d/default.conf